title: Mahmoud Mousa
logo: IMG_0130.jpeg  # Add this image if you want a personal logo or headshot
description: >
  Data Analyst | Digital Marketing Specialist | Data-Driven Thinker  
  Based in Krakow, Poland – Experienced in Google Analytics, SQL, Python, Power BI, and more.
show_downloads: false
theme: jekyll-theme-minimal

# Optional social links (uncomment if using)
# github_username: Saadm1811
# linkedin_username: your-linkedin-username
